[workspace]
members = ["evm", "field", "maybe_rayon", "plonky2", "starky", "util", "u32", "ecdsa", "plonky2_crypto"]

[profile.release]
opt-level = 3
#lto = "fat"
#codegen-units = 1

[profile.bench]
opt-level = 3
